// AUTH //
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USER_INFO = "GET_USER_INFO";
export const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER";
export const REGISTER_USER_LOADING = "REGISTER_USER_LOADING";
export const CREATE_NEW_USER = "CREATE_NEW_USER";

// ERRORS
export const ERROR_LOADING = "ERROR_LOADING";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
